FormFlow/FormFlow/Areas/Admin/Controllers/StepTypesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using FormFlow.Models;

namespace FormFlow.Areas.Admin.Controllers
{
    public class StepTypesController : Controller
    {
        private FormFlowEntities db = new FormFlowEntities();

        //
        // GET: /Admin/StepTypes/

        public ActionResult Index()
        {
            return View(db.StepTypes.ToList());
        }

        //
        // GET: /Admin/StepTypes/Details/5

        public ActionResult Details(Guid? id = null)
        {
            StepType steptype = db.StepTypes.Find(id);
            if (steptype == null)
            {
                return HttpNotFound();
            }
            return View(steptype);
        }

        //
        // GET: /Admin/StepTypes/Create

        public ActionResult Create()
        {
            return View();
        }

        //
        // POST: /Admin/StepTypes/Create

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(StepType steptype)
        {
            if (ModelState.IsValid)
            {
                steptype.ID = Guid.NewGuid();
                db.StepTypes.Add(steptype);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(steptype);
        }

        //
        // GET: /Admin/StepTypes/Edit/5

        public ActionResult Edit(Guid? id = null)
        {
            StepType steptype = db.StepTypes.Find(id);
            if (steptype == null)
            {
                return HttpNotFound();
            }
            return View(steptype);
        }

        //
        // POST: /Admin/StepTypes/Edit/5

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(StepType steptype)
        {
            if (ModelState.IsValid)
            {
                db.Entry(steptype).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(steptype);
        }

        //
        // GET: /Admin/StepTypes/Delete/5

        public ActionResult Delete(Guid? id = null)
        {
            StepType steptype = db.StepTypes.Find(id);
            if (steptype == null)
            {
                return HttpNotFound();
            }
            return View(steptype);
        }

        //
        // POST: /Admin/StepTypes/Delete/5

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(Guid id)
        {
            StepType steptype = db.StepTypes.Find(id);
            db.StepTypes.Remove(steptype);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            db.Dispose();
            base.Dispose(disposing);
        }
    }
}

FormFlow/FormFlow/Areas/Admin/Controllers/TransitionTypesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using FormFlow.Models;

namespace FormFlow.Areas.Admin.Controllers
{
    public class TransitionTypesController : Controller
    {
        private FormFlowEntities db = new FormFlowEntities();

        //
        // GET: /Admin/TransitionTypes/

        public ActionResult Index()
        {
            return View(db.TransitionTypes.ToList());
        }

        //
        // GET: /Admin/TransitionTypes/Details/5

        public ActionResult Details(Guid? id = null)
        {
            TransitionType transitiontype = db.TransitionTypes.Find(id);
            if (transitiontype == null)
            {
                return HttpNotFound();
            }
            return View(transitiontype);
        }

        //
        // GET: /Admin/TransitionTypes/Create

        public ActionResult Create()
        {
            return View();
        }

        //
        // POST: /Admin/TransitionTypes/Create

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(TransitionType transitiontype)
        {
            if (ModelState.IsValid)
            {
                transitiontype.ID = Guid.NewGuid();
                db.TransitionTypes.Add(transitiontype);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(transitiontype);
        }

        //
        // GET: /Admin/TransitionTypes/Edit/5

        public ActionResult Edit(Guid? id = null)
        {
            TransitionType transitiontype = db.TransitionTypes.Find(id);
            if (transitiontype == null)
            {
                return HttpNotFound();
            }
            return View(transitiontype);
        }

        //
        // POST: /Admin/TransitionTypes/Edit/5

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(TransitionType transitiontype)
        {
            if (ModelState.IsValid)
            {
                db.Entry(transitiontype).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(transitiontype);
        }

        //
        // GET: /Admin/TransitionTypes/Delete/5

        public ActionResult Delete(Guid? id = null)
        {
            TransitionType transitiontype = db.TransitionTypes.Find(id);
            if (transitiontype == null)
            {
                return HttpNotFound();
            }
            return View(transitiontype);
        }

        //
        // POST: /Admin/TransitionTypes/Delete/5

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(Guid id)
        {
            TransitionType transitiontype = db.TransitionTypes.Find(id);
            db.TransitionTypes.Remove(transitiontype);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            db.Dispose();
            base.Dispose(disposing);
        }
    }
}

FormFlow/FormFlow/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8" />
        <title>@ViewBag.Title - My ASP.NET MVC Application</title>
        <link href="~/favicon.ico" rel="shortcut icon" type="image/x-icon" />
        <meta name="viewport" content="width=device-width" />
        @Styles.Render("~/Content/css")
        @Scripts.Render("~/bundles/modernizr")
    </head>
    <body>
        <header>
            <div class="content-wrapper">
                <div class="float-left">
                    <p class="site-title">@Html.ActionLink("~ Form ~ Flow ~", "Index", "Home")</p>
                </div>
                <div class="float-right">
                    <section id="login">
                        @Html.Partial("_LoginPartial")
                    </section>
                    <nav>
                        <ul id="menu">
                            <li>@Html.ActionLink("Flows", "Index", "Flows", new {area = "Admin"}, null)</li>
                            <li>@Html.ActionLink("Step Types", "Index", "StepTypes", new {area = "Admin"}, null)</li>
                            <li>@Html.ActionLink("Steps", "Index", "Steps", new {area = "Admin"}, null)</li>
                            <li>@Html.ActionLink("Transition Types", "Index", "TransitionTypes", new {area = "Admin"}, null)</li>
                            <li>@Html.ActionLink("Transitions", "Index", "Transitions", new {area = "Admin"}, null)</li>
                        </ul>
                    </nav>
                </div>
            </div>
        </header>
        <div id="body">
            @RenderSection("featured", required: false)
            <section class="content-wrapper main-content clear-fix">
                @RenderBody()
            </section>
        </div>
        <footer>
            <div class="content-wrapper">
                <div class="float-left">
                    <p>&copy; @DateTime.Now.Year - My ASP.NET MVC Application</p>
                </div>
            </div>
        </footer>

        @Scripts.Render("~/bundles/jquery")
        @RenderSection("scripts", required: false)
    </body>
</html>